// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClwR1GPBxlGEgHBDNqBbkvOhbl_xxhky8',
    appId: '1:628462719016:android:6eabd6e7040c70af93251d',
    messagingSenderId: '628462719016',
    projectId: 'todo-list-provider-97c3c',
    storageBucket: 'todo-list-provider-97c3c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzl_204GTv6JlXAFU94dpMAz2Lswb9sWE',
    appId: '1:628462719016:ios:f15ffc8bb0b1379193251d',
    messagingSenderId: '628462719016',
    projectId: 'todo-list-provider-97c3c',
    storageBucket: 'todo-list-provider-97c3c.appspot.com',
    androidClientId: '628462719016-13kemf4bknea0o5bparsd53e4uop7m8r.apps.googleusercontent.com',
    iosClientId: '628462719016-iu5lukpb6rs33dpli65su2q8siel83qk.apps.googleusercontent.com',
    iosBundleId: 'br.dev.jailtonmendes.todoListProvider',
  );
}
